### ISSUE TITLE
Melhor indicação de onde começa a linha do tempo das Tramitações

### ISSUE THREAD

**Issue by diCaminha** [gladguys/polis#320]
**Descreva a solução desejada**
Seria ideal e mais claro se indicassemos onde que é o início e o fim da linha do tempo na tela de tramitações, pois quando há tramites em apenas uma data, você não sabe bem qual é o estado atual daquela proposição.

**Comment by rodrigobastosv** [comment]
Ordenar de maneira reversa as tramitacoes
