### ISSUE TITLE
Ordenação de procurar deputados não funcionando corretamente

### ISSUE THREAD

**Issue by diCaminha** [gladguys/polis#372]
**Descreva qual o BUG**
Deputados que começam com a letra A estão no fim da lista

**Passos para reproduzir**
1.  ir na tela de pesquisar politicos
2. descer no scroll até os últimos políticos

**Screenshots**
![image](https://user-images.githubusercontent.com/5836109/83550547-62c49700-a4dd-11ea-9c1b-99b1c65b2b79.png)

**Comment by rodrigobastosv** [comment]
https://pub.dev/packages/diacritic
