### ISSUE TITLE
Tela congelada ao fazer login

### ISSUE THREAD

**Issue by diCaminha** [gladguys/polis#63]
Sequência de passos:
1. fiz sign up para novo usuario
2. fiz login com esse novo usuario
3. aparentemente é feita a autenticação, porém fica na tela abaixo:

![image](https://user-images.githubusercontent.com/5836109/77383869-c8203d00-6d62-11ea-9ff1-9c4dee2903c0.png)

![image](https://user-images.githubusercontent.com/5836109/77384609-91e3bd00-6d64-11ea-9ffd-ecaa46e228d1.png)

**Comment by rodrigobastosv** [comment]
Vimos que foi uma instabilidade no firebase. Fechando
