### ISSUE TITLE
Criar contador para numero de seguidos

### ISSUE THREAD

**Issue by diCaminha** [gladguys/polis#92]
para uma melhor performance na tela de profile politico, deve ser criado uma logica que contabiliza o numero de usuarios que seguem o politico.

sugestão:
- criar uma function que vai ser disparada toda vida que um usuario segue ou para de seguir um político.
- essa função vai incrementar ou decrementar um contador que pode ficar dentro do document do politico.

**Comment by rodrigobastosv** [comment]
Isso já foi feito!
